;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        exit-recursive-edit
        prelude-move-beginning-of-line
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-lt-gt
        ))
