;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-window
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        exit-recursive-edit
        prelude-move-beginning-of-line
        sp-delete-char
        sp-kill-hybrid-sexp
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-lt-gt
        ))
